"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useAuth } from "@clerk/nextjs";
import {
  ReactFlow,
  Background,
  Controls,
  MiniMap,
  addEdge,
  useNodesState,
  useEdgesState,
  type OnConnect,
  type Viewport,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";

import MindMapNode from "./MindMapNode";
import StickyNoteNode from "./StickyNoteNode";
import ImageNode from "./ImageNode";
import MindMapToolbar from "./MindMapToolbar";
import GeneratingOverlay from "./GeneratingOverlay";
import ExplainPanel from "./ExplainPanel";
import { NodeActionsContext } from "./NodeActionsContext";
import { appendChildNodes, buildGraphFromAi } from "@/lib/layout";
import { api } from "@/lib/api";
import type {
  FileAttachment,
  FlowEdge,
  FlowNode,
  GraphData,
  ImageFlowNode,
  StickyNoteFlowNode,
} from "@/lib/types";

type AnyNode = FlowNode | StickyNoteFlowNode | ImageFlowNode;

const nodeTypes = {
  mindMapNode: MindMapNode,
  stickyNote: StickyNoteNode,
  imageNode: ImageNode,
};

interface MindMapCanvasProps {
  mindMapId: string;
  initialTitle: string;
  initialGraph: GraphData;
  token: string;
  initialTopic?: string | null;
}

export default function MindMapCanvas({
  mindMapId,
  initialTitle,
  initialGraph,
  initialTopic,
}: MindMapCanvasProps) {
  const { getToken } = useAuth();
  const [nodes, setNodes, onNodesChange] = useNodesState<AnyNode>(
    (initialGraph.nodes as AnyNode[]) ?? []
  );
  const [edges, setEdges, onEdgesChange] = useEdgesState<FlowEdge>(
    (initialGraph.edges as FlowEdge[]) ?? []
  );
  const [title, setTitle] = useState(initialTitle);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatingTopic, setGeneratingTopic] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  const [expandingNodeId, setExpandingNodeId] = useState<string | null>(null);
  const [explainingNodeId, setExplainingNodeId] = useState<string | null>(null);
  const [explainPanel, setExplainPanel] = useState<{ label: string; text: string | null } | null>(null);
  const autoGeneratedRef = useRef(false);
  const autoSaveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isFirstRenderRef = useRef(true);
  const viewportRef = useRef<Viewport>(
    initialGraph.viewport ?? { x: 0, y: 0, zoom: 1 }
  );

  const onConnect: OnConnect = useCallback(
    (params) => setEdges((eds) => addEdge(params, eds)),
    [setEdges]
  );

  // ── AI Generation ──────────────────────────────────────────────────────
  const handleGenerate = async (topic: string, attachment?: FileAttachment) => {
    setIsGenerating(true);
    setGeneratingTopic(topic);
    try {
      const token = await getToken();
      const result = await api.ai.generate(topic, token!, attachment);
      const { nodes: newNodes, edges: newEdges } = buildGraphFromAi(result.nodes);

      // Preserve any existing freeform nodes (sticky notes, images)
      const freeformNodes = nodes.filter(
        (n) => n.type === "stickyNote" || n.type === "imageNode"
      );
      setNodes([...newNodes, ...freeformNodes] as AnyNode[]);
      setEdges(newEdges);

      const newTitle = title === "Untitled Mind Map" ? result.title : title;
      if (title === "Untitled Mind Map") setTitle(newTitle);

      // Auto-save so the map is never lost on refresh
      await api.mindmaps.update(
        mindMapId,
        {
          title: newTitle,
          graph_data: {
            nodes: [...newNodes, ...freeformNodes],
            edges: newEdges,
            viewport: viewportRef.current,
          } as GraphData,
        },
        token!
      );
    } catch (err) {
      console.error("Generation failed:", err);
      alert("Failed to generate mind map. Please try again.");
    } finally {
      setIsGenerating(false);
      setGeneratingTopic("");
    }
  };

  // ── Add child node manually ────────────────────────────────────────────
  const handleAddChild = useCallback(
    (parentId: string) => {
      const maxId = Math.max(
        0,
        ...nodes.map((n) => parseInt(n.id) || 0)
      );
      const newId = String(maxId + 1);
      const parentNode = nodes.find((n) => n.id === parentId);

      setNodes((nds) => [
        ...nds,
        {
          id: newId,
          type: "mindMapNode",
          position: {
            x: (parentNode?.position.x ?? 0) + 240,
            y: parentNode?.position.y ?? 0,
          },
          data: { label: "New Idea", nodeType: "sub" },
        } as FlowNode,
      ]);
      setEdges((eds) => [
        ...eds,
        {
          id: `e-${parentId}-${newId}`,
          source: parentId,
          target: newId,
          type: "smoothstep",
        },
      ]);
    },
    [nodes, setNodes, setEdges]
  );

  // ── AI Expand ─────────────────────────────────────────────────────────
  const handleAiExpand = useCallback(
    async (nodeId: string, nodeLabel: string) => {
      setExpandingNodeId(nodeId);
      try {
        const token = await getToken();
        const result = await api.ai.expand(nodeLabel, title, token!);
        const labels = result.nodes.map((n) => n.label);

        // Only pass mindMapNodes to dagre layout; freeform nodes stay in place
        const mindMapNodes = nodes.filter(
          (n): n is FlowNode => n.type === "mindMapNode"
        );
        const freeformNodes = nodes.filter(
          (n) => n.type === "stickyNote" || n.type === "imageNode"
        );

        const { nodes: updatedMindMapNodes, edges: updatedEdges } =
          appendChildNodes(mindMapNodes, edges, nodeId, labels);

        setNodes([...updatedMindMapNodes, ...freeformNodes] as AnyNode[]);
        setEdges(updatedEdges);
      } catch (err) {
        console.error("Expand failed:", err);
        alert("Failed to expand node. Please try again.");
      } finally {
        setExpandingNodeId(null);
      }
    },
    [getToken, nodes, edges, title, setNodes, setEdges]
  );

  // ── AI Explain ────────────────────────────────────────────────────────
  const handleAiExplain = useCallback(
    async (nodeId: string, nodeLabel: string) => {
      setExplainingNodeId(nodeId);
      setExplainPanel({ label: nodeLabel, text: null });
      try {
        const token = await getToken();
        const result = await api.ai.explain(nodeLabel, title, token!);
        setExplainPanel({ label: nodeLabel, text: result.explanation });
      } catch (err) {
        console.error("Explain failed:", err);
        setExplainPanel(null);
        alert("Failed to explain node. Please try again.");
      } finally {
        setExplainingNodeId(null);
      }
    },
    [getToken, title]
  );

  // ── Sticky note ───────────────────────────────────────────────────────
  const handleAddStickyNote = useCallback(() => {
    const newId = `sticky-${Date.now()}`;
    const stickyNote: StickyNoteFlowNode = {
      id: newId,
      type: "stickyNote",
      position: { x: Math.random() * 400 + 100, y: Math.random() * 200 + 100 },
      data: { text: "", color: "#fef08a" },
    };
    setNodes((nds) => [...nds, stickyNote]);
  }, [setNodes]);

  // ── Board image upload ────────────────────────────────────────────────
  const handleAddImage = useCallback(
    (src: string, filename: string) => {
      const newId = `image-${Date.now()}`;
      const imageNode: ImageFlowNode = {
        id: newId,
        type: "imageNode",
        position: { x: Math.random() * 300 + 150, y: Math.random() * 200 + 150 },
        data: { src, filename },
      };
      setNodes((nds) => [...nds, imageNode]);
    },
    [setNodes]
  );

  // ── Auto-generate on mount (from dashboard topic) ─────────────────────
  useEffect(() => {
    if (initialTopic && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      handleGenerate(initialTopic);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // ── Debounced auto-save (2s after last change) ─────────────────────────
  useEffect(() => {
    // Skip the very first render to avoid saving on mount
    if (isFirstRenderRef.current) {
      isFirstRenderRef.current = false;
      return;
    }
    // Don't auto-save while generating (handleGenerate does its own save)
    if (isGenerating) return;

    if (autoSaveTimerRef.current) clearTimeout(autoSaveTimerRef.current);

    autoSaveTimerRef.current = setTimeout(async () => {
      try {
        const token = await getToken();
        await api.mindmaps.update(
          mindMapId,
          {
            title,
            graph_data: {
              nodes,
              edges,
              viewport: viewportRef.current,
            } as GraphData,
          },
          token!
        );
        setIsSaving(false);
      } catch (err) {
        console.error("Auto-save failed:", err);
      }
    }, 2000);

    setIsSaving(true); // show indicator immediately while debounce is pending

    return () => {
      if (autoSaveTimerRef.current) clearTimeout(autoSaveTimerRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [nodes, edges, title]);

  // ── Save ──────────────────────────────────────────────────────────────
  const handleSave = async () => {
    setIsSaving(true);
    try {
      const token = await getToken();
      await api.mindmaps.update(
        mindMapId,
        {
          title,
          graph_data: { nodes, edges, viewport: viewportRef.current } as GraphData,
        },
        token!
      );
    } catch (err) {
      console.error("Save failed:", err);
      alert("Failed to save. Please try again.");
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <NodeActionsContext.Provider
      value={{
        onAddChild: handleAddChild,
        onAiExpand: handleAiExpand,
        onAiExplain: handleAiExplain,
        expandingNodeId,
        explainingNodeId,
      }}
    >
      <div className="flex flex-col h-screen bg-slate-950">
        <MindMapToolbar
          title={title}
          isGenerating={isGenerating}
          onTitleChange={setTitle}
          onGenerate={handleGenerate}
          onSave={handleSave}
          isSaving={isSaving}
          onAddStickyNote={handleAddStickyNote}
          onAddImage={handleAddImage}
        />

        <div className="flex-1 relative">
          {isGenerating && <GeneratingOverlay topic={generatingTopic} />}
          {explainPanel && (
            <ExplainPanel
              nodeLabel={explainPanel.label}
              explanation={explainPanel.text}
              isLoading={explainingNodeId !== null}
              onClose={() => setExplainPanel(null)}
            />
          )}
          <ReactFlow
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onConnect={onConnect}
            nodeTypes={nodeTypes}
            // Restore saved viewport; only fitView on brand-new maps with no saved viewport
            defaultViewport={initialGraph.viewport ?? { x: 0, y: 0, zoom: 1 }}
            fitView={!initialGraph.viewport}
            fitViewOptions={{ padding: 0.2 }}
            onMoveEnd={(_, viewport) => { viewportRef.current = viewport; }}
            defaultEdgeOptions={{ type: "smoothstep", animated: false }}
          >
            <Background color="#2d3748" gap={24} size={1} />
            <Controls className="!bg-slate-800 !border-slate-700 !text-white" />
            <MiniMap
              nodeColor={(n) => {
                if (n.type === "stickyNote") return "#eab308";
                if (n.type === "imageNode") return "#3b82f6";
                const data = n.data as { nodeType?: string };
                if (data.nodeType === "central") return "#6366f1";
                if (data.nodeType === "branch") return "#475569";
                return "#334155";
              }}
              className="!bg-slate-900 !border-slate-700"
            />
          </ReactFlow>
        </div>
      </div>
    </NodeActionsContext.Provider>
  );
}
